---
title: "pathway_mutual_exclusivity"
output: html_document
date: "2023-09-30"
---

# call some libraries
```{r setup}
library(data.table)
library(here)
library(survival)
library(survminer)
library(tidytable)
library(WeightIt)
library(cobalt)
library(cowplot)
library(jskm)
library(survey)
library(stringdist)
library(stringr)
library(RColorBrewer)
library(tidytext)
library(corrplot)
library(survival) # contains survival examples, handle survival objects
library(caret) # for stratified cross validiation
library(dplyr) # data manipulation
library(pec) # prediction error curves
library(zoo)

load("/Users/thinhtran/Documents/Data/Genomics/all_missense_process_nsclc_0927.RData")
load("/Users/thinhtran/Documents/Data/Genomics/NSCLC_IMPACT_clinical_subset.RData")
load("/Users/thinhtran/Documents/Data/Knowledge_Base/Pathways.Rdata")

load("/Users/thinhtran/Documents/Data/Knowledge_Base/Pathways.Rdata")
load("/Users/thinhtran/Documents/Data/Genomics/IMPACT_gam_oncogenic.RData")
load("/Users/thinhtran/Documents/Data/Genomics/IMPACT_genomics_oncokb.RData")
load("/Users/thinhtran/Documents/Data/Genomics/all_missense_process_nsclc_0927.RData")
load("/Users/thinhtran/Documents/Data/Genomics/NSCLC_IMPACT_clinical_subset.RData")

source("utils.R")
pathway_list <- unique(pathways_df$Pathway)

```

# Mutual exclusivity test
```{r}

pathway_list_totest <- c("NRF2", "RTK_RAS", "TP53_Pathway")

pathway_data <- pathway_results_oncogenic <- pathway_count_oncogenic <- pathway_results_benign <- pathway_count_benign <- list()

method_list <- sub("_binary|_Rescue", "", grep("_binary|_Rescue", colnames(all_missense_process_nsclc), value=T))

for (i in 1:length(pathway_list_totest)){
  tmpp <- pathway_list_totest[i]
  tmp_gene_list <- intersect(pathways_df[Pathway == tmpp, ]$Gene, unique(all_missense_process_nsclc$Hugo_Symbol))
  cat("\n",tmpp)
  tmp_pathway <- processGeneList(tmpp, maf=all_missense_process_nsclc,  clinical = pt_subset)

  # tmp_pathway <- pathway_data[[i]]
  
  cat("\nTesting one vs all - oncogenic")

  tmp_results <- testMutualExclusivity(pathway=tmp_pathway, gene_list=tmp_gene_list,
                                       side2="oncogenic", pairwise = F, oncokb_included = F, methods = method_list)

  tmp_result_process <- resultDTProcess(tmp_results, tmpp)
  
  pathway_count_oncogenic[[i]] <- tmp_result_process$count
  pathway_results_oncogenic[[i]] <- tmp_result_process$results
  
  cat("\nTesting one vs all - benign")

  tmp_results <- testMutualExclusivity(pathway=tmp_pathway, gene_list=tmp_gene_list, 
                                       side2="benign", pairwise = F, oncokb_included = F, methods = method_list)

  tmp_result_process <- resultDTProcess(tmp_results, tmpp)
  
  pathway_count_benign[[i]] <- tmp_result_process$count
  pathway_results_benign[[i]] <- tmp_result_process$results


}

pathway_oncogenic <- resultListProcess(results_df = pathway_results_oncogenic,
                                    count_df = pathway_count_oncogenic)

pathway_benign <- resultListProcess(results_df = pathway_results_benign,
                                    count_df = pathway_count_benign)

library(forcats)
g1 <- ggplot(pathway_oncogenic$count, aes(y=fct_rev(method), x=pathway, fill=V1*100))+
  geom_tile()+
  scale_fill_gradientn(colors = brewer.pal(9, 'Blues'), na.value = "lightgrey", limits=c(0,70))+
  theme_minimal() +
  coord_fixed() +
  rotate_x_text(angle=45)+
  #facet_grid(~ method)+
  labs(fill="% One vs all\nMutually exclusive", x="", y="Methods")+
  theme(legend.position = "none")
 
g2 <- ggplot(pathway_benign$count, aes(y=fct_rev(method), x=pathway, fill=V1*100))+
  geom_tile()+
  scale_fill_gradientn(colors = brewer.pal(9, 'Blues'), na.value = "lightgrey", limits=c(0,70))+
  theme_minimal() +
  coord_fixed() +
  rotate_x_text(angle=45)+
  #facet_grid(~ method)+
  labs(fill="% One vs all\nMutually exclusive", x="", y="")


plot_grid(g1, g2, nrow=1, align="h", axis="b", rel_widths = c(1, 1.15), labels="AUTO")

```

# Calculate OR_mutex
```{r calculate or}

### Odds ratio ###

total_or <- rbind(pathway_oncogenic[, mutex := ifelse(pval.adj <= 0.05 & logOR <= 0, 1, 0)][, .N, by=.(mutex, method)][, rescue_oncogenic := 1],
                  pathway_benign[, mutex := ifelse(pval.adj <= 0.05 & logOR <= 0, 1, 0)][, .N, by=.(mutex, method)][, rescue_oncogenic := 0])

### Fisher's
method_count <- total_or[, .N, by=method]

data_split <- split(total_or[method %in% method_count[N ==4,]$method, ], by="method")

fishers <- lapply(data_split, function(sub_data) {
  # Create the 2x2 contingency table for mutex and rescue_oncogenic
  table_data <- xtabs(N ~ mutex + rescue_oncogenic, data = sub_data)
  print(table_data)
  
  # Perform Fisher's exact test
  fisher_result <- fisher.test(table_data)
  
  # Return a data frame with the method name, p-value, odds ratio, and confidence intervals
  data.frame(
    method = unique(sub_data$method),
    p_value = fisher_result$p.value,
    odds_ratio = fisher_result$estimate,
    conf_int_low = fisher_result$conf.int[1],
    conf_int_high = fisher_result$conf.int[2]
  )
})

# Combine the results into a single data frame
fishers <- do.call(rbind, fishers)

fishers <- setDT(fishers)
fishers <- fishers[, method := ifelse(method == "VARITY_R_LOO", "VARITY", method)]
fishers <- fishers[, `:=`(log_or = log(odds_ratio),
                          log_conf_low = log(conf_int_low),
                          log_conf_high = log(conf_int_high))]

ggplot(unique(fishers[!method %in% c("ClinVar", "oncogenic", "BoostDM"),]),
       aes(x=reorder(method, -odds_ratio), y=odds_ratio))+
  geom_bar(stat="identity", position="dodge")+
  theme_classic()+
  scale_y_continuous(expand=c(0,0))+
  geom_hline(yintercept = 1, color="red")+
  geom_errorbar(aes(ymin=conf_int_low, ymax=conf_int_high), width=.2,
               position=position_dodge(.9)) +
  rotate_x_text(angle=45)+
  labs(x="Method", y="Odds ratio of mutual exclusivity of\n reclassified oncogenic vs. reclassified benign mutations")

ggsave(file="expanded_manuscript/Final_Figures/Raw_PDFs/pathway_exclusivity_results_or_1001.pdf",
       width=7,  height=4.5, units="in")


```

